// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('GUITesting', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('GUITesting', async function() {
    await driver.get("https://www.power.fi/")
    await driver.manage().window().setRect({ width: 1280, height: 712 })
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).click()
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).sendKeys("iPhone 13 pro")
    await driver.findElement(By.css(".search-product:nth-child(6) .product-name > font > font")).click()
    await driver.executeScript("window.scrollTo(0,39)")
    await driver.executeScript("window.scrollTo(0,978)")
    await driver.findElement(By.css(".mb-spacer-mini > img")).click()
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).click()
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).sendKeys("iPhone 12 pro")
    await driver.findElement(By.linkText("iPhone 12 Pro")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.executeScript("window.scrollTo(0,712)")
    await driver.findElement(By.css("em > a > font > font")).click()
    await driver.executeScript("window.scrollTo(0,589)")
    await driver.executeScript("window.scrollTo(0,387)")
    await driver.executeScript("window.scrollTo(0,127.5)")
    await driver.executeScript("window.scrollTo(0,3319.5)")
    await driver.findElement(By.css(".mb-spacer-mini > img")).click()
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).click()
    await driver.executeScript("window.scrollTo(0,349)")
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).sendKeys("iPhone 12")
    await driver.findElement(By.linkText("iPhone 12 Pro")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.executeScript("window.scrollTo(0,466)")
    await driver.findElement(By.css(".btn-row:nth-child(3) font > font")).click()
    await driver.findElement(By.css("#product-391030464 .swiper-wrapper")).click()
    await driver.executeScript("window.scrollTo(0,9861.5)")
    await driver.findElement(By.css("#product-39171074 .swiper-slide:nth-child(1) .product-stickers")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.executeScript("window.scrollTo(0,212)")
    await driver.executeScript("window.scrollTo(0,962)")
    {
      const element = await driver.findElement(By.css(".btn > .ng-star-inserted > font > font"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".btn > .ng-star-inserted > font > font")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".ng-star-inserted > .pwr-btn")).click()
    await driver.findElement(By.css(".modal-header > .close > .ng-tns-c168-10")).click()
    {
      const element = await driver.findElement(By.linkText("Shopping basket 1 425 €"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".mb-spacer-mini > img")).click()
    {
      const element = await driver.findElement(By.css(".text-nowrap > font > font"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".text-nowrap > font > font")).click()
    await driver.executeScript("window.scrollTo(0,14)")
    await driver.findElement(By.css(".pwr-icon-trash")).click()
    {
      const element = await driver.findElement(By.css(".pwr-btn > .ng-star-inserted"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".section-checkout-basket__item__remove > font > font")).click()
    await driver.executeScript("window.scrollTo(0,70)")
    await driver.findElement(By.linkText("Go back to the store")).click()
  })
})
