// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('iPhone 13 pro', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('iPhone 13 pro', async function() {
    await driver.get("https://www.power.fi/")
    await driver.manage().window().setRect({ width: 1280, height: 712 })
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).click()
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).sendKeys("iphone 13 pro ")
    await driver.findElement(By.css(".search-product:nth-child(6) .product-name")).click()
    {
      const element = await driver.findElement(By.css(".mb-spacer-mini > img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".mb-spacer-mini > img")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).click()
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).sendKeys("iphone 12 pro ")
    await driver.findElement(By.linkText("iPhone 12 Pro")).click()
    await driver.executeScript("window.scrollTo(0,786)")
    await driver.executeScript("window.scrollTo(0,1850)")
    await driver.executeScript("window.scrollTo(0,3666)")
    await driver.executeScript("window.scrollTo(0,4854)")
    await driver.findElement(By.css(".mb-spacer-mini > img")).click()
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).click()
    await driver.findElement(By.css(".ng-tns-c76-1 > .search-input")).sendKeys("iphone 12")
    await driver.findElement(By.linkText("iPhone 12 Pro")).click()
    await driver.findElement(By.css(".btn-row:nth-child(3) > .btn")).click()
    await driver.findElement(By.css("#product-933220845 .swiper-slide:nth-child(1) .lazyloaded:nth-child(3)")).click()
    await driver.executeScript("window.scrollTo(0,95)")
    await driver.executeScript("window.scrollTo(0,951)")
    await driver.findElement(By.css(".btn > .ng-star-inserted > font > font")).click()
    {
      const element = await driver.findElement(By.css(".btn-mega"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".ng-star-inserted > .pwr-btn")).click()
    await driver.findElement(By.css(".modal-header > .close > .ng-tns-c168-4")).click()
    {
      const element = await driver.findElement(By.linkText("Shopping basket 1 425 €"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".mb-spacer-mini > img")).click()
    await driver.findElement(By.css(".text-nowrap > font > font")).click()
    await driver.executeScript("window.scrollTo(0,191)")
    await driver.findElement(By.css(".pwr-icon-trash")).click()
    {
      const element = await driver.findElement(By.css(".secondary > div"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,245)")
    await driver.findElement(By.css(".section-checkout-basket__item__remove > font > font")).click()
    await driver.executeScript("window.scrollTo(0,162)")
    await driver.findElement(By.css(".mt-spacer-mini > .pwr-btn font > font")).click()
    {
      const element = await driver.findElement(By.css(".mt-spacer-mini > .pwr-btn font > font"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
